# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: William Bowditch
title: SecureWorks Software Enginner, Edinburgh Napier Masters Student
email: bc.bowditch@gmail.com
website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: wb_ml_sec
github_username:  wbowditch
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: wbowditch
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a Boston College graduate working in the Edinburgh office of SecureWorks, as well as pursuing a part time MSc at Edinburgh Napier Univeristy in Advanced Security and Digitial Forensics.

  My work consists of developing the SecureWorks Machine Learning Engine [Foresee](https://www.secureworks.com/blog/foresee-human-and-machine-learning-working-together) and our User Entity Behaviour Analysis using [Apache Spark](https://spark.apache.org) 
  
  I am most skilled in: <mark>Java</mark>,<mark>Python</mark>,<mark>Scala</mark>, and <mark>AWS</mark>


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in machine learning and cybersecurity some of my other interests and hobbies are:
   - Bouldering
   - Dungeons & Dragons
   - Rowing

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
