# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: William Bowditch
title: SecureWorks Software Enginner, Edinburgh Napier Masters Student
email: bc.bowditch@gmail.com
website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: wb_ml_sec
github_username:  wbowditch
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: wbowditch
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a software engineer working in the Edinburgh office of SecureWorks, as well as pursuing an MSc at Edinburgh Napier Univeristy in Advanced Security and Digitial Forensics.

  My work spread across many big data analytical projects, but mainly consists of developing [Foresee](https://www.secureworks.com/blog/foresee-human-and-machine-learning-working-together) and [User Behaviour Analytics](https://en.wikipedia.org/wiki/User_behavior_analytics)
  
  I am most skilled in: <mark>Java</mark>, <mark>Python</mark>, <mark>Scala</mark>, and <mark>AWS</mark>


# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in machine learning and cybersecurity some of my other interests and hobbies are:
   - Bouldering
   - Dungeons & Dragons
   - Rowing

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
